
graphql:
      servlet:
           mapping: /graphiql
           enabled: true
           corsEnabled: true
           # if you want to @ExceptionHandler annotation for custom GraphQLErrors
           exception-handlers-enabled: true
           contextSetting: PER_REQUEST_WITH_INSTRUMENTATION